[2023-08-28T00:01:53.205+0000] {processor.py:157} INFO - Started process (PID=30) to work on /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:01:53.206+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/DagFetcher.py for tasks to queue
[2023-08-28T00:01:53.210+0000] {logging_mixin.py:151} INFO - [2023-08-28T00:01:53.209+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:01:53.324+0000] {logging_mixin.py:151} INFO - [2023-08-28T00:01:53.319+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/DagFetcher.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/DagFetcher.py", line 6, in <module>
    airflow_bucket = Variable.get('airflow_bucket_dags')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable airflow_bucket_dags does not exist'
[2023-08-28T00:01:53.326+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:01:53.351+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/DagFetcher.py took 0.152 seconds
[2023-08-28T00:02:23.628+0000] {processor.py:157} INFO - Started process (PID=85) to work on /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:02:23.630+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/DagFetcher.py for tasks to queue
[2023-08-28T00:02:23.638+0000] {logging_mixin.py:151} INFO - [2023-08-28T00:02:23.636+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:02:23.740+0000] {logging_mixin.py:151} INFO - [2023-08-28T00:02:23.732+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/DagFetcher.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/DagFetcher.py", line 6, in <module>
    airflow_bucket = Variable.get('airflow_bucket_dags')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable airflow_bucket_dags does not exist'
[2023-08-28T00:02:23.741+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:02:23.772+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/DagFetcher.py took 0.148 seconds
[2023-08-28T00:02:54.413+0000] {processor.py:157} INFO - Started process (PID=140) to work on /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:02:54.415+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/DagFetcher.py for tasks to queue
[2023-08-28T00:02:54.420+0000] {logging_mixin.py:151} INFO - [2023-08-28T00:02:54.419+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:02:54.509+0000] {logging_mixin.py:151} INFO - [2023-08-28T00:02:54.505+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/DagFetcher.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/DagFetcher.py", line 6, in <module>
    airflow_bucket = Variable.get('airflow_bucket_dags')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable airflow_bucket_dags does not exist'
[2023-08-28T00:02:54.510+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:02:54.532+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/DagFetcher.py took 0.124 seconds
[2023-08-28T00:03:24.711+0000] {processor.py:157} INFO - Started process (PID=194) to work on /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:03:24.713+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/DagFetcher.py for tasks to queue
[2023-08-28T00:03:24.719+0000] {logging_mixin.py:151} INFO - [2023-08-28T00:03:24.718+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:03:24.890+0000] {logging_mixin.py:151} INFO - [2023-08-28T00:03:24.877+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/DagFetcher.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/DagFetcher.py", line 6, in <module>
    airflow_bucket = Variable.get('airflow_bucket_dags')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable airflow_bucket_dags does not exist'
[2023-08-28T00:03:24.896+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:03:24.938+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/DagFetcher.py took 0.238 seconds
[2023-08-28T00:03:55.132+0000] {processor.py:157} INFO - Started process (PID=249) to work on /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:03:55.133+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/DagFetcher.py for tasks to queue
[2023-08-28T00:03:55.138+0000] {logging_mixin.py:151} INFO - [2023-08-28T00:03:55.137+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:03:55.284+0000] {logging_mixin.py:151} INFO - [2023-08-28T00:03:55.280+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/DagFetcher.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/DagFetcher.py", line 6, in <module>
    airflow_bucket = Variable.get('airflow_bucket_dags')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable airflow_bucket_dags does not exist'
[2023-08-28T00:03:55.285+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:03:55.309+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/DagFetcher.py took 0.182 seconds
[2023-08-28T00:04:25.580+0000] {processor.py:157} INFO - Started process (PID=304) to work on /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:04:25.583+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/DagFetcher.py for tasks to queue
[2023-08-28T00:04:25.588+0000] {logging_mixin.py:151} INFO - [2023-08-28T00:04:25.588+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:04:25.751+0000] {logging_mixin.py:151} INFO - [2023-08-28T00:04:25.741+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/DagFetcher.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/DagFetcher.py", line 6, in <module>
    airflow_bucket = Variable.get('airflow_bucket_dags')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable airflow_bucket_dags does not exist'
[2023-08-28T00:04:25.758+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:04:25.796+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/DagFetcher.py took 0.221 seconds
[2023-08-28T00:04:55.889+0000] {processor.py:157} INFO - Started process (PID=359) to work on /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:04:55.891+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/DagFetcher.py for tasks to queue
[2023-08-28T00:04:55.894+0000] {logging_mixin.py:151} INFO - [2023-08-28T00:04:55.893+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:04:55.974+0000] {logging_mixin.py:151} INFO - [2023-08-28T00:04:55.970+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/DagFetcher.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/DagFetcher.py", line 6, in <module>
    airflow_bucket = Variable.get('airflow_bucket_dags')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable airflow_bucket_dags does not exist'
[2023-08-28T00:04:55.977+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:04:56.003+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/DagFetcher.py took 0.120 seconds
[2023-08-28T00:05:26.524+0000] {processor.py:157} INFO - Started process (PID=414) to work on /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:05:26.539+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/DagFetcher.py for tasks to queue
[2023-08-28T00:05:26.578+0000] {logging_mixin.py:151} INFO - [2023-08-28T00:05:26.575+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:08:37.142+0000] {processor.py:157} INFO - Started process (PID=32) to work on /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:08:37.145+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/DagFetcher.py for tasks to queue
[2023-08-28T00:08:37.163+0000] {logging_mixin.py:151} INFO - [2023-08-28T00:08:37.161+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:08:37.469+0000] {logging_mixin.py:151} INFO - [2023-08-28T00:08:37.441+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/DagFetcher.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/DagFetcher.py", line 6, in <module>
    airflow_bucket = Variable.get('airflow_bucket_dags')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable airflow_bucket_dags does not exist'
[2023-08-28T00:08:37.475+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:08:37.532+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/DagFetcher.py took 0.399 seconds
[2023-08-28T00:09:07.916+0000] {processor.py:157} INFO - Started process (PID=86) to work on /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:09:07.923+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/DagFetcher.py for tasks to queue
[2023-08-28T00:09:07.939+0000] {logging_mixin.py:151} INFO - [2023-08-28T00:09:07.936+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:09:08.140+0000] {logging_mixin.py:151} INFO - [2023-08-28T00:09:08.131+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/DagFetcher.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/DagFetcher.py", line 6, in <module>
    airflow_bucket = Variable.get('airflow_bucket_dags')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable airflow_bucket_dags does not exist'
[2023-08-28T00:09:08.142+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:09:08.218+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/DagFetcher.py took 0.317 seconds
[2023-08-28T00:09:38.419+0000] {processor.py:157} INFO - Started process (PID=141) to work on /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:09:38.421+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/DagFetcher.py for tasks to queue
[2023-08-28T00:09:38.425+0000] {logging_mixin.py:151} INFO - [2023-08-28T00:09:38.424+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:09:38.526+0000] {logging_mixin.py:151} INFO - [2023-08-28T00:09:38.522+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/DagFetcher.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/DagFetcher.py", line 6, in <module>
    airflow_bucket = Variable.get('airflow_bucket_dags')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable airflow_bucket_dags does not exist'
[2023-08-28T00:09:38.527+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:09:38.548+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/DagFetcher.py took 0.133 seconds
[2023-08-28T00:10:09.337+0000] {processor.py:157} INFO - Started process (PID=196) to work on /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:10:09.339+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/DagFetcher.py for tasks to queue
[2023-08-28T00:10:09.345+0000] {logging_mixin.py:151} INFO - [2023-08-28T00:10:09.344+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:10:09.432+0000] {logging_mixin.py:151} INFO - [2023-08-28T00:10:09.428+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/DagFetcher.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/DagFetcher.py", line 6, in <module>
    airflow_bucket = Variable.get('airflow_bucket_dags')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable airflow_bucket_dags does not exist'
[2023-08-28T00:10:09.434+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:10:09.457+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/DagFetcher.py took 0.125 seconds
[2023-08-28T00:10:39.614+0000] {processor.py:157} INFO - Started process (PID=251) to work on /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:10:39.616+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/DagFetcher.py for tasks to queue
[2023-08-28T00:10:39.623+0000] {logging_mixin.py:151} INFO - [2023-08-28T00:10:39.622+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:10:39.720+0000] {logging_mixin.py:151} INFO - [2023-08-28T00:10:39.716+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/DagFetcher.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/DagFetcher.py", line 6, in <module>
    airflow_bucket = Variable.get('airflow_bucket_dags')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable airflow_bucket_dags does not exist'
[2023-08-28T00:10:39.721+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:10:39.742+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/DagFetcher.py took 0.133 seconds
[2023-08-28T00:11:09.945+0000] {processor.py:157} INFO - Started process (PID=306) to work on /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:11:09.948+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/DagFetcher.py for tasks to queue
[2023-08-28T00:11:09.953+0000] {logging_mixin.py:151} INFO - [2023-08-28T00:11:09.952+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:11:10.043+0000] {logging_mixin.py:151} INFO - [2023-08-28T00:11:10.039+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/DagFetcher.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/DagFetcher.py", line 6, in <module>
    airflow_bucket = Variable.get('airflow_bucket_dags')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable airflow_bucket_dags does not exist'
[2023-08-28T00:11:10.044+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:11:10.064+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/DagFetcher.py took 0.124 seconds
[2023-08-28T00:11:40.109+0000] {processor.py:157} INFO - Started process (PID=360) to work on /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:11:40.111+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/DagFetcher.py for tasks to queue
[2023-08-28T00:11:40.115+0000] {logging_mixin.py:151} INFO - [2023-08-28T00:11:40.114+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:11:40.193+0000] {logging_mixin.py:151} INFO - [2023-08-28T00:11:40.190+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/DagFetcher.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/DagFetcher.py", line 6, in <module>
    airflow_bucket = Variable.get('airflow_bucket_dags')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable airflow_bucket_dags does not exist'
[2023-08-28T00:11:40.194+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:11:40.215+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/DagFetcher.py took 0.112 seconds
[2023-08-28T00:12:10.617+0000] {processor.py:157} INFO - Started process (PID=414) to work on /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:12:10.619+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/DagFetcher.py for tasks to queue
[2023-08-28T00:12:10.624+0000] {logging_mixin.py:151} INFO - [2023-08-28T00:12:10.623+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:12:10.783+0000] {logging_mixin.py:151} INFO - [2023-08-28T00:12:10.778+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/DagFetcher.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/DagFetcher.py", line 6, in <module>
    airflow_bucket = Variable.get('airflow_bucket_dags')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable airflow_bucket_dags does not exist'
[2023-08-28T00:12:10.786+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:12:10.813+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/DagFetcher.py took 0.201 seconds
[2023-08-28T00:12:41.189+0000] {processor.py:157} INFO - Started process (PID=469) to work on /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:12:41.191+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/DagFetcher.py for tasks to queue
[2023-08-28T00:12:41.195+0000] {logging_mixin.py:151} INFO - [2023-08-28T00:12:41.195+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:12:41.281+0000] {logging_mixin.py:151} INFO - [2023-08-28T00:12:41.277+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/DagFetcher.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/DagFetcher.py", line 6, in <module>
    airflow_bucket = Variable.get('airflow_bucket_dags')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable airflow_bucket_dags does not exist'
[2023-08-28T00:12:41.282+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:12:41.311+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/DagFetcher.py took 0.125 seconds
[2023-08-28T00:13:11.464+0000] {processor.py:157} INFO - Started process (PID=524) to work on /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:13:11.467+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/DagFetcher.py for tasks to queue
[2023-08-28T00:13:11.476+0000] {logging_mixin.py:151} INFO - [2023-08-28T00:13:11.475+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:13:11.630+0000] {logging_mixin.py:151} INFO - [2023-08-28T00:13:11.623+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/DagFetcher.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/DagFetcher.py", line 6, in <module>
    airflow_bucket = Variable.get('airflow_bucket_dags')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable airflow_bucket_dags does not exist'
[2023-08-28T00:13:11.634+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:13:11.670+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/DagFetcher.py took 0.211 seconds
[2023-08-28T00:13:41.741+0000] {processor.py:157} INFO - Started process (PID=578) to work on /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:13:41.744+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/DagFetcher.py for tasks to queue
[2023-08-28T00:13:41.747+0000] {logging_mixin.py:151} INFO - [2023-08-28T00:13:41.747+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:13:41.832+0000] {logging_mixin.py:151} INFO - [2023-08-28T00:13:41.828+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/DagFetcher.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/DagFetcher.py", line 6, in <module>
    airflow_bucket = Variable.get('airflow_bucket_dags')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable airflow_bucket_dags does not exist'
[2023-08-28T00:13:41.833+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:13:41.852+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/DagFetcher.py took 0.114 seconds
[2023-08-28T00:14:12.095+0000] {processor.py:157} INFO - Started process (PID=633) to work on /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:14:12.097+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/DagFetcher.py for tasks to queue
[2023-08-28T00:14:12.101+0000] {logging_mixin.py:151} INFO - [2023-08-28T00:14:12.101+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:14:12.186+0000] {logging_mixin.py:151} INFO - [2023-08-28T00:14:12.183+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/DagFetcher.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/DagFetcher.py", line 6, in <module>
    airflow_bucket = Variable.get('airflow_bucket_dags')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable airflow_bucket_dags does not exist'
[2023-08-28T00:14:12.187+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:14:12.206+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/DagFetcher.py took 0.117 seconds
[2023-08-28T00:14:43.096+0000] {processor.py:157} INFO - Started process (PID=688) to work on /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:14:43.099+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/DagFetcher.py for tasks to queue
[2023-08-28T00:14:43.106+0000] {logging_mixin.py:151} INFO - [2023-08-28T00:14:43.105+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:14:43.205+0000] {logging_mixin.py:151} INFO - [2023-08-28T00:14:43.198+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/DagFetcher.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/DagFetcher.py", line 6, in <module>
    airflow_bucket = Variable.get('airflow_bucket_dags')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable airflow_bucket_dags does not exist'
[2023-08-28T00:14:43.208+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:14:43.233+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/DagFetcher.py took 0.146 seconds
[2023-08-28T00:15:14.056+0000] {processor.py:157} INFO - Started process (PID=743) to work on /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:15:14.059+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/DagFetcher.py for tasks to queue
[2023-08-28T00:15:14.061+0000] {logging_mixin.py:151} INFO - [2023-08-28T00:15:14.061+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:15:14.132+0000] {logging_mixin.py:151} INFO - [2023-08-28T00:15:14.129+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/DagFetcher.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/DagFetcher.py", line 6, in <module>
    airflow_bucket = Variable.get('airflow_bucket_dags')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable airflow_bucket_dags does not exist'
[2023-08-28T00:15:14.133+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:15:14.151+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/DagFetcher.py took 0.098 seconds
[2023-08-28T00:15:44.765+0000] {processor.py:157} INFO - Started process (PID=798) to work on /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:15:44.767+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/DagFetcher.py for tasks to queue
[2023-08-28T00:15:44.771+0000] {logging_mixin.py:151} INFO - [2023-08-28T00:15:44.770+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:15:44.851+0000] {logging_mixin.py:151} INFO - [2023-08-28T00:15:44.847+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/DagFetcher.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/DagFetcher.py", line 6, in <module>
    airflow_bucket = Variable.get('airflow_bucket_dags')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable airflow_bucket_dags does not exist'
[2023-08-28T00:15:44.853+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:15:44.875+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/DagFetcher.py took 0.116 seconds
[2023-08-28T00:16:15.451+0000] {processor.py:157} INFO - Started process (PID=853) to work on /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:16:15.452+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/DagFetcher.py for tasks to queue
[2023-08-28T00:16:15.456+0000] {logging_mixin.py:151} INFO - [2023-08-28T00:16:15.455+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:16:15.534+0000] {logging_mixin.py:151} INFO - [2023-08-28T00:16:15.531+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/DagFetcher.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/DagFetcher.py", line 6, in <module>
    airflow_bucket = Variable.get('airflow_bucket_dags')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable airflow_bucket_dags does not exist'
[2023-08-28T00:16:15.536+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:16:15.555+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/DagFetcher.py took 0.108 seconds
[2023-08-28T00:16:45.711+0000] {processor.py:157} INFO - Started process (PID=908) to work on /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:16:45.713+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/DagFetcher.py for tasks to queue
[2023-08-28T00:16:45.716+0000] {logging_mixin.py:151} INFO - [2023-08-28T00:16:45.715+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:16:45.798+0000] {logging_mixin.py:151} INFO - [2023-08-28T00:16:45.794+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/DagFetcher.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/DagFetcher.py", line 6, in <module>
    airflow_bucket = Variable.get('airflow_bucket_dags')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable airflow_bucket_dags does not exist'
[2023-08-28T00:16:45.799+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:16:45.820+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/DagFetcher.py took 0.113 seconds
[2023-08-28T00:17:16.368+0000] {processor.py:157} INFO - Started process (PID=963) to work on /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:17:16.370+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/DagFetcher.py for tasks to queue
[2023-08-28T00:17:16.373+0000] {logging_mixin.py:151} INFO - [2023-08-28T00:17:16.372+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:17:16.454+0000] {logging_mixin.py:151} INFO - [2023-08-28T00:17:16.445+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/DagFetcher.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/DagFetcher.py", line 6, in <module>
    airflow_bucket = Variable.get('airflow_bucket_dags')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable airflow_bucket_dags does not exist'
[2023-08-28T00:17:16.455+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:17:16.473+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/DagFetcher.py took 0.109 seconds
[2023-08-28T00:17:47.125+0000] {processor.py:157} INFO - Started process (PID=1018) to work on /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:17:47.129+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/DagFetcher.py for tasks to queue
[2023-08-28T00:17:47.158+0000] {logging_mixin.py:151} INFO - [2023-08-28T00:17:47.156+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:17:47.656+0000] {logging_mixin.py:151} INFO - [2023-08-28T00:17:47.642+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/DagFetcher.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/DagFetcher.py", line 6, in <module>
    airflow_bucket = Variable.get('airflow_bucket_dags')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable airflow_bucket_dags does not exist'
[2023-08-28T00:17:47.660+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:17:47.719+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/DagFetcher.py took 0.615 seconds
[2023-08-28T00:18:18.503+0000] {processor.py:157} INFO - Started process (PID=1071) to work on /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:18:18.538+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/DagFetcher.py for tasks to queue
[2023-08-28T00:18:18.608+0000] {logging_mixin.py:151} INFO - [2023-08-28T00:18:18.606+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:18:19.124+0000] {logging_mixin.py:151} INFO - [2023-08-28T00:18:19.089+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/DagFetcher.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/DagFetcher.py", line 6, in <module>
    airflow_bucket = Variable.get('airflow_bucket_dags')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable airflow_bucket_dags does not exist'
[2023-08-28T00:18:19.141+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:18:19.195+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/DagFetcher.py took 0.757 seconds
[2023-08-28T00:18:50.023+0000] {processor.py:157} INFO - Started process (PID=1132) to work on /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:18:50.026+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/DagFetcher.py for tasks to queue
[2023-08-28T00:18:50.033+0000] {logging_mixin.py:151} INFO - [2023-08-28T00:18:50.032+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:18:50.140+0000] {logging_mixin.py:151} INFO - [2023-08-28T00:18:50.135+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/DagFetcher.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/DagFetcher.py", line 6, in <module>
    airflow_bucket = Variable.get('airflow_bucket_dags')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable airflow_bucket_dags does not exist'
[2023-08-28T00:18:50.142+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:18:50.176+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/DagFetcher.py took 0.157 seconds
[2023-08-28T00:19:20.527+0000] {processor.py:157} INFO - Started process (PID=1186) to work on /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:19:20.529+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/DagFetcher.py for tasks to queue
[2023-08-28T00:19:20.539+0000] {logging_mixin.py:151} INFO - [2023-08-28T00:19:20.535+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:19:20.678+0000] {logging_mixin.py:151} INFO - [2023-08-28T00:19:20.670+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/DagFetcher.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/DagFetcher.py", line 6, in <module>
    airflow_bucket = Variable.get('airflow_bucket_dags')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable airflow_bucket_dags does not exist'
[2023-08-28T00:19:20.686+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:19:20.740+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/DagFetcher.py took 0.219 seconds
[2023-08-28T00:19:51.157+0000] {processor.py:157} INFO - Started process (PID=1241) to work on /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:19:51.161+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/DagFetcher.py for tasks to queue
[2023-08-28T00:19:51.169+0000] {logging_mixin.py:151} INFO - [2023-08-28T00:19:51.167+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:19:51.289+0000] {logging_mixin.py:151} INFO - [2023-08-28T00:19:51.284+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/DagFetcher.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/DagFetcher.py", line 6, in <module>
    airflow_bucket = Variable.get('airflow_bucket_dags')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable airflow_bucket_dags does not exist'
[2023-08-28T00:19:51.290+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:19:51.338+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/DagFetcher.py took 0.189 seconds
[2023-08-28T00:20:21.786+0000] {processor.py:157} INFO - Started process (PID=1296) to work on /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:20:21.788+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/DagFetcher.py for tasks to queue
[2023-08-28T00:20:21.793+0000] {logging_mixin.py:151} INFO - [2023-08-28T00:20:21.792+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:20:21.868+0000] {logging_mixin.py:151} INFO - [2023-08-28T00:20:21.864+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/DagFetcher.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/DagFetcher.py", line 6, in <module>
    airflow_bucket = Variable.get('airflow_bucket_dags')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable airflow_bucket_dags does not exist'
[2023-08-28T00:20:21.869+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:20:21.897+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/DagFetcher.py took 0.115 seconds
[2023-08-28T00:20:52.892+0000] {processor.py:157} INFO - Started process (PID=1351) to work on /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:20:52.898+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/DagFetcher.py for tasks to queue
[2023-08-28T00:20:52.911+0000] {logging_mixin.py:151} INFO - [2023-08-28T00:20:52.910+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:20:53.001+0000] {logging_mixin.py:151} INFO - [2023-08-28T00:20:52.998+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/DagFetcher.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/DagFetcher.py", line 6, in <module>
    airflow_bucket = Variable.get('airflow_bucket_dags')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable airflow_bucket_dags does not exist'
[2023-08-28T00:20:53.002+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:20:53.025+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/DagFetcher.py took 0.143 seconds
[2023-08-28T00:21:23.214+0000] {processor.py:157} INFO - Started process (PID=1406) to work on /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:21:23.219+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/DagFetcher.py for tasks to queue
[2023-08-28T00:21:23.226+0000] {logging_mixin.py:151} INFO - [2023-08-28T00:21:23.225+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:21:23.310+0000] {logging_mixin.py:151} INFO - [2023-08-28T00:21:23.307+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/DagFetcher.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/DagFetcher.py", line 6, in <module>
    airflow_bucket = Variable.get('airflow_bucket_dags')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable airflow_bucket_dags does not exist'
[2023-08-28T00:21:23.312+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:21:23.332+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/DagFetcher.py took 0.125 seconds
[2023-08-28T00:21:54.127+0000] {processor.py:157} INFO - Started process (PID=1461) to work on /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:21:54.134+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/DagFetcher.py for tasks to queue
[2023-08-28T00:21:54.144+0000] {logging_mixin.py:151} INFO - [2023-08-28T00:21:54.143+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:21:54.327+0000] {logging_mixin.py:151} INFO - [2023-08-28T00:21:54.318+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/DagFetcher.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/DagFetcher.py", line 6, in <module>
    airflow_bucket = Variable.get('airflow_bucket_dags')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable airflow_bucket_dags does not exist'
[2023-08-28T00:21:54.333+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/DagFetcher.py
[2023-08-28T00:21:54.365+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/DagFetcher.py took 0.257 seconds
